//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public Animals()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_gender { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> height { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual AnimalType AnimalType { get; set; }
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
