//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int appointment_id { get; set; }
        public Nullable<int> animal_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public System.DateTime appointment_date { get; set; }
        public string comment { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Doctors Doctors { get; set; }
    }
}
