//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public Doctors()
        {
            this.Appointments = new HashSet<Appointments>();
            this.User = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public Nullable<int> id_type { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual TypeDoctor TypeDoctor { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
