//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinaryClinicEntities : DbContext
    {
        public VeterinaryClinicEntities()
            : base("name=VeterinaryClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Animals> Animals { get; set; }
        public DbSet<AnimalType> AnimalType { get; set; }
        public DbSet<Appointments> Appointments { get; set; }
        public DbSet<Doctors> Doctors { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeDoctor> TypeDoctor { get; set; }
        public DbSet<User> User { get; set; }
    }
}
