//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDoctor
    {
        public TypeDoctor()
        {
            this.Doctors = new HashSet<Doctors>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Doctors> Doctors { get; set; }
    }
}
